modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0"
showAsResourcePack=false

[[mods]]
modId="chronodawn"
version="${version}"
displayName="Chrono Dawn"
description='''
A time manipulation themed Minecraft mod featuring the Chrono Dawn dimension.
Explore a frozen dimension, defeat time-controlling bosses, and master ultimate artifacts.
'''
logoFile="chronodawn_logo.png"
authors="ksoichiro"
credits="Built with Architectury"
displayURL="https://github.com/ksoichiro/ChronoDawn"

[[mixins]]
config="chronodawn-neoforge.mixins.json"

[[dependencies.chronodawn]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.chronodawn]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.chronodawn]]
modId="architectury"
type="required"
versionRange="[13.0.8,)"
ordering="AFTER"
side="BOTH"
